apiVersion: v1
kind: Pod
metadata:
  name: eureka-server
  labels:
    app: eureka-server
    release: "0"
spec:
  containers:
  - name: eureka-server-container
    image:  eureka_server:1.0
    ports:
      - containerPort: 8761
    imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service                 #name of the service
  labels:
    app: eureka-server-service                    
spec:
  type : NodePort
  ports:
  - port: 8761
  selector:
    app: eureka-server             #selecting the pod with lable value  